### ISSUE TITLE
Minor: Variables in type expression of TESSSearch download definition

### ISSUE THREAD

**Issue by d-giles** [tylerapritchard/lksearch#10]
```python 
 def download(
        self,
        cloud: PREFER_CLOUD = True,
        cache: PREFER_CLOUD = True,
        cloud_only: PREFER_CLOUD = False,
        download_dir: PACKAGEDIR = default_download_dir,
        # TESScut_product="SPOC",
        TESScut_size=10,
):
```

`PREFER_CLOUD` and `PACKAGEDIR` are probably supposed to be `bool` and `str` respectively. Perhaps these are supposed to be default values?

**Comment by Nschanche** [comment]
Good catch, looks like the typing slipped here. I've also added the ENABLE_CACHE in config, as I don't think we intended to use the same key for cloud, cache, and cloud_only. 

`
  def download(
        self,
        cloud: bool = PREFER_CLOUD,
        cache: bool = ENABLE_CACHE,
        cloud_only: bool = DOWNLOAD_CLOUD,
        download_dir: str = default_download_dir,
        # TESScut_product="SPOC",
        TESScut_size: int =10,
):

`

**Comment by Nschanche** [comment]
Good catch, the typing got off here. We also over-used the PREFER_CLOUD parameter. I've fixed to the following:
 ```
    def download(
        self,
        cloud: bool = PREFER_CLOUD,
        cloud_only: bool = DOWNLOAD_CLOUD,
        download_dir: str = default_download_dir,
        cache: bool = True,
        # TESScut_product="SPOC",
        TESScut_size: int =10,
    ):
```
